export default {
  NEW_TICKET_CLICK: 'NEW_TICKET_CLICK',
  TICKET_UPDATE: 'TICKET_UPDATE',
  SEARCH_CHANGE: 'SEARCH_CHANGE',
  TICKET_MODULE_SHOW_CLICK: 'TICKET_MODULE_SHOW_CLICK',
  TICKET_MODULE_EDIT_CLICK: 'TICKET_MODULE_EDIT_CLICK',
  TICKET_MODULE_HIDE_CLICK: 'TICKET_MODULE_HIDE_CLICK',
}