export default {
  NEW_TICKET: 'NEW_TICKET',
  UPDATE_TICKET: 'UPDATE_TICKET',
  SEARCH_CHANGE: 'SEARCH_CHANGE',
  SHOW_TICKET_MODULE: 'SHOW_TICKET_MODULE',
  HIDE_TICKET_MODULE: 'HIDE_TICKET_MODULE',
}